-- MySQL Script generated by MySQL Workbench
-- Fri Sep 19 02:46:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vinculacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vinculacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vinculacion` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vinculacion` ;

-- -----------------------------------------------------
-- Table `vinculacion`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`auditoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `actor_tipo` ENUM('empresa', 'usuario', 'sistema') NOT NULL,
  `actor_id` BIGINT NULL DEFAULT NULL,
  `accion` VARCHAR(100) NOT NULL,
  `entidad` VARCHAR(100) NOT NULL,
  `entidad_id` BIGINT NULL DEFAULT NULL,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `ts` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_auditoria_entidad` (`entidad` ASC, `entidad_id` ASC) VISIBLE,
  INDEX `idx_auditoria_actor` (`actor_tipo` ASC, `actor_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`auditoria_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`auditoria_detalle` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `auditoria_id` BIGINT NOT NULL,
  `campo` VARCHAR(100) NOT NULL,
  `campo_label` VARCHAR(150) NOT NULL,
  `valor_anterior` TEXT NULL DEFAULT NULL,
  `valor_nuevo` TEXT NULL DEFAULT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_auditoria_detalle_auditoria` (`auditoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_detalle_auditoria`
    FOREIGN KEY (`auditoria_id`)
    REFERENCES `vinculacion`.`auditoria` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`empresa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(191) NOT NULL,
  `rfc` VARCHAR(20) NULL DEFAULT NULL,
  `contacto_nombre` VARCHAR(191) NULL DEFAULT NULL,
  `contacto_email` VARCHAR(191) NULL DEFAULT NULL,
  `telefono` VARCHAR(30) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  `creado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_empresa_rfc` (`rfc` ASC) VISIBLE,
  INDEX `idx_empresa_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`convenio` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `empresa_id` BIGINT NOT NULL,
  `estatus` ENUM('pendiente', 'en_revision', 'vigente', 'vencido') NOT NULL DEFAULT 'pendiente',
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `version_actual` VARCHAR(100) NULL DEFAULT NULL,
  `creado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_convenio_empresa` (`empresa_id` ASC, `estatus` ASC) VISIBLE,
  CONSTRAINT `fk_convenio_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `vinculacion`.`empresa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`doc_tipo_ss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`doc_tipo_ss` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `periodo_num` INT NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `obligatorio` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_doc_tipo_ss` (`periodo_num` ASC, `nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`estudiante` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(191) NOT NULL,
  `matricula` VARCHAR(50) NOT NULL,
  `carrera` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(191) NULL DEFAULT NULL,
  `telefono` VARCHAR(30) NULL DEFAULT NULL,
  `creado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_estudiante_matricula` (`matricula` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`plaza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`plaza` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(191) NOT NULL,
  `empresa_id` BIGINT NULL DEFAULT NULL,
  `direccion` VARCHAR(191) NULL DEFAULT NULL,
  `cupo` INT NULL DEFAULT NULL,
  `activa` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `idx_plaza_empresa` (`empresa_id` ASC, `activa` ASC) VISIBLE,
  CONSTRAINT `fk_plaza_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `vinculacion`.`empresa` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`servicio` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `estudiante_id` BIGINT NOT NULL,
  `plaza_id` BIGINT NULL DEFAULT NULL,
  `estatus` ENUM('prealta', 'activo', 'concluido', 'cancelado') NOT NULL DEFAULT 'prealta',
  `horas_acumuladas` INT NOT NULL DEFAULT '0',
  `creado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_serv_est` (`estudiante_id` ASC, `estatus` ASC) VISIBLE,
  INDEX `idx_serv_plaza` (`plaza_id` ASC) VISIBLE,
  CONSTRAINT `fk_serv_estudiante`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `vinculacion`.`estudiante` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_serv_plaza`
    FOREIGN KEY (`plaza_id`)
    REFERENCES `vinculacion`.`plaza` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`periodo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `servicio_id` BIGINT NOT NULL,
  `numero` INT NOT NULL,
  `estatus` ENUM('abierto', 'en_revision', 'completado') NOT NULL DEFAULT 'abierto',
  `abierto_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cerrado_en` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_periodo_serv_num` (`servicio_id` ASC, `numero` ASC) VISIBLE,
  INDEX `idx_periodo_estatus` (`estatus` ASC) VISIBLE,
  CONSTRAINT `fk_periodo_servicio`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `vinculacion`.`servicio` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`descarga_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`descarga_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `estudiante_id` BIGINT NOT NULL,
  `periodo_id` BIGINT NOT NULL,
  `doc_tipo_id` BIGINT NOT NULL,
  `descargado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_descarga_est_per` (`estudiante_id` ASC, `periodo_id` ASC) VISIBLE,
  INDEX `idx_descarga_doc` (`doc_tipo_id` ASC) VISIBLE,
  INDEX `fk_descarga_periodo` (`periodo_id` ASC) VISIBLE,
  CONSTRAINT `fk_descarga_doctipo`
    FOREIGN KEY (`doc_tipo_id`)
    REFERENCES `vinculacion`.`doc_tipo_ss` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_descarga_est`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `vinculacion`.`estudiante` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_descarga_periodo`
    FOREIGN KEY (`periodo_id`)
    REFERENCES `vinculacion`.`periodo` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`doc_ss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`doc_ss` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `periodo_id` BIGINT NOT NULL,
  `tipo_id` BIGINT NOT NULL,
  `ruta` VARCHAR(255) NULL DEFAULT NULL,
  `recibido` TINYINT(1) NOT NULL DEFAULT '0',
  `estatus` ENUM('pendiente', 'aprobado', 'rechazado') NOT NULL DEFAULT 'pendiente',
  `observacion` TEXT NULL DEFAULT NULL,
  `actualizado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_doc_ss` (`periodo_id` ASC, `tipo_id` ASC) VISIBLE,
  INDEX `idx_docss_periodo` (`periodo_id` ASC, `estatus` ASC) VISIBLE,
  INDEX `fk_docss_tipo` (`tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_docss_periodo`
    FOREIGN KEY (`periodo_id`)
    REFERENCES `vinculacion`.`periodo` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_docss_tipo`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `vinculacion`.`doc_tipo_ss` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`documento_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`documento_tipo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `obligatorio` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_documento_tipo_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`documento` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `empresa_id` BIGINT NOT NULL,
  `convenio_id` BIGINT NULL DEFAULT NULL,
  `tipo_id` BIGINT NOT NULL,
  `ruta` VARCHAR(255) NOT NULL,
  `estatus` ENUM('pendiente', 'aprobado', 'rechazado') NOT NULL DEFAULT 'pendiente',
  `observacion` TEXT NULL DEFAULT NULL,
  `creado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_doc_empresa` (`empresa_id` ASC) VISIBLE,
  INDEX `idx_doc_convenio` (`convenio_id` ASC) VISIBLE,
  INDEX `idx_doc_tipo` (`tipo_id` ASC, `estatus` ASC) VISIBLE,
  CONSTRAINT `fk_doc_convenio`
    FOREIGN KEY (`convenio_id`)
    REFERENCES `vinculacion`.`convenio` (`id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_doc_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `vinculacion`.`empresa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_doc_tipo`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `vinculacion`.`documento_tipo` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`machote_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`machote_comentario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `convenio_id` BIGINT NOT NULL,
  `clausula` VARCHAR(20) NOT NULL,
  `comentario` TEXT NOT NULL,
  `creado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_mc_convenio` (`convenio_id` ASC, `clausula` ASC) VISIBLE,
  CONSTRAINT `fk_mc_convenio`
    FOREIGN KEY (`convenio_id`)
    REFERENCES `vinculacion`.`convenio` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`portal_acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`portal_acceso` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `empresa_id` BIGINT NOT NULL,
  `token` CHAR(36) NOT NULL,
  `nip_hash` VARCHAR(255) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `creado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_portal_token` (`token` ASC) VISIBLE,
  INDEX `idx_portal_empresa` (`empresa_id` ASC, `activo` ASC) VISIBLE,
  CONSTRAINT `fk_portal_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `vinculacion`.`empresa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vinculacion`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinculacion`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `rol` ENUM('res_admin', 'editor', 'capturista', 'ss_admin', 'estudiante') NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `creado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estudiante_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_usuario_email` (`email` ASC) VISIBLE,
  INDEX `idx_usuario_rol` (`rol` ASC) VISIBLE,
  INDEX `fk_usuario_estudiante` (`estudiante_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_estudiante`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `vinculacion`.`estudiante` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
